name: 🐛 Bug report
description: Report a reproducible bug or regression
labels: ["bug", "frontend"]
assignees: 
  - Basilissa108 
  - BartoszWu
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        Thanks for contributing by creating an issue! ❤️
  - type: mardown
    id: Description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the challenge you are running into.
    validations:
      required: false
