name:  💡 Feature request
description: Suggest a new idea for design system
labels: ["frontend"]
assignees: 
  - Basilissa108 
  - BartoszWu
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        Thanks for contributing by creating an issue! ❤️
  - type: dropdown
    id: complexity
    attributes:
      label: Type of request 
      description: What kind of request you are asking for.
      options:
        - Small design tweak to existing components
        - Bigger change to an existing component
        - Create an entirely new component
    validations:
      required: true
  - type: textarea
    id: Description
    attributes:
      label: Describe the feature you'd like to request
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation and context
      description: Tell us why this change is needed or helpfull, and what problem is may help to solve. If possible put business reasons for this request.
    validations:
      required: true
  - type: textarea
    id: timeline
    attributes:
      label: Specific timeline issues / requests
      description: Do you want this work within a specific time period? Is it blocking you with your task?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
  - type: checkboxes
    id: terms
    attributes:
      label: Do you want to contribute this feature and create a pull request
      options:
        - label: Yes I will be happy to contribute
  - type: checkboxes
    id: epic
    attributes:
      label: Zenhub
      description: Assign ticket to `Design System Pod` in the `Epics` so it will be immediately visible in Design system board 
      options:
        - label:  Ticket is assigned to **Design System Pod** epic
          required: true